### ISSUE TITLE
Cocoapods installation

### ISSUE THREAD

**Issue by m4riusz** [CombineCommunity/CombineCocoa#13]
Installation via
`pod 'CombineCocoa'` -> instals old version `0.0.1` instead of `0.1.0`
`pod 'CombineCocoa', '~> 0.1.0'` -> fails 
`[!] CocoaPods could not find compatible versions for pod "CombineCocoa":
  In Podfile:
    CombineCocoa (~> 0.1.0)`
Only way to install version `0.1.0` is
`pod 'CombineCocoa', :git => 'https://github.com/CombineCommunity/CombineCocoa.git', :tag => '0.1.0'`

Cocoapods version:`1.8.4`

**Comment by freak4pc** [comment]
Had an issue with the upload apparently, should be good now!
