### ISSUE TITLE
ControlProperty & ControlEvent don't call removeTarget in cancel method

### ISSUE THREAD

**Issue by c0diq** [CombineCommunity/CombineCocoa#14]
Both classes invoke `control.addTarget(self, action: #selector(handleEvent), for: event)` but forget to call `control.removeTarget` in `cancel` method leaving a reference to `self`. Since the target is not retained, it is possible that it is not causing an issue though (it may be weak inside the control) but it would be preferable to be consistent and follow Apple recommendation "To stop the delivery of events, always call the removeTarget(_:action:for:) method."

**Comment by freak4pc** [comment]
Hey there ! From my tests there is no issue since the reference is weak but I’m happy to accept a PR to add that on cancellation :)

**Comment by freak4pc** [comment]
Added in 681cb06669f16f71fc3be32f32096f1468eeb511
