### ISSUE TITLE
How can I add a textPublisher to UITextView?

### ISSUE THREAD

**Issue by kevinrenskers** [CombineCommunity/CombineCocoa#19]
Since `UITextView` doesn't subclass `UIControl` I can't just do something like this 

```
public extension UITextView {
    /// A publisher emitting any text changes to a this text field.
    var textPublisher: AnyPublisher<String?, Never> {
        Publishers.ControlProperty(control: self, events: [.allEditingEvents, .valueChanged], keyPath: \.text)
                  .eraseToAnyPublisher()
    }
}
```

So how would you add such a publisher?

**Comment by kevinrenskers** [comment]
Ah, I guess that's what #10 is for?

**Comment by jdisho** [comment]
That's right @kevinrenskers :)

**Comment by kevinrenskers** [comment]
I see that #21 is merged, any chance this is going to result in a new release soon? Would be lovely to have this functionality :)

**Comment by freak4pc** [comment]
Yup, I also added the actual publisher in #24 @kevinrenskers 
Once it's merged I'll cut a release.
