### ISSUE TITLE
how to send a new output for UITextfiled

### ISSUE THREAD

**Issue by xysT2W** [CombineCommunity/CombineCocoa#22]
if i set a subsriber for UITextfield's textPublisher,

and i changed the UITextfield's content by code like this:

```
textField.text = "some value"
```

that subscriber can't receive the output.

so, can i send a signal by myself?

something like this:

```
textField.textPublisher.send("some Value")
```

**Comment by freak4pc** [comment]
Hey @xysT2W - 
1. Please don't file something a bug unless it's a bug :) 
2. Please don't tag individual members, this is a community project. This lets other people come in and help. 

`ControlEventPublisher` listens on a control event. If you change the value programatically, you should send it: 

```swift
textField.sendActions(for: .editingDidEnd)
```

**Comment by xysT2W** [comment]
> Hey @xysT2W -
> 
> 1. Please don't file something a bug unless it's a bug :)
> 2. Please don't tag individual members, this is a community project. This lets other people come in and help.
> 
> `ControlEventPublisher` listens on a control event. If you change the value programatically, you should send it:
> 
> ```swift
> textField.sendActions(for: .editingDidEnd)
> ```

I'm sorry.

The 'bug tag' and 'tag individual members' is the default option.
