### ISSUE TITLE
No framework output when using Carthage

### ISSUE THREAD

**Issue by Prince2k3** [CombineCommunity/CombineCocoa#23]
**Describe the bug**

**To Reproduce**
1. Add "CombineCommunity/CombineCocoa" to Cartfile
2. Run Carthage update --platform iOS 

**Expected behavior**
CombineCocoa builds and produces CombineCocoa.framework

**What is happening** 

Following message appears during Carthage process 

```
*** Skipped building CombineCocoa due to the error:
Dependency "CombineCocoa" has no shared framework schemes for any of the platforms: iOS
```
**Device:**
 - CombineCocoa version - latest

**Comment by freak4pc** [comment]
Please don’t assign people to bug you open. 
Thanks for reporting.

**Comment by Prince2k3** [comment]
@freak4pc  I didn't .. it did that on its own

**Comment by freak4pc** [comment]
That’s strange... I’ll check. Thanks !

**Comment by freak4pc** [comment]
This is fixed in https://github.com/CombineCommunity/CombineCocoa/pull/26
