### ISSUE TITLE
Can't create my own delegate-based publishers

### ISSUE THREAD

**Issue by kevinrenskers** [CombineCommunity/CombineCocoa#28]
I'm trying to add some publishers to UISearchBarDelegate like this:

``` swift
extension UISearchBar {
  var searchBarSearchButtonClicked: AnyPublisher<UISearchBar, Never> {
    let selector = #selector(UISearchBarDelegate.searchBarSearchButtonClicked(_:))

    return delegateProxy
      .interceptSelectorPublisher(selector)
      .map { $0[1] as! UISearchBar }
      .eraseToAnyPublisher()
  }

  private var delegateProxy: UISearchBarDelegateProxy {
      .createDelegateProxy(for: self)
  }
}

private class UISearchBarDelegateProxy: DelegateProxy, UISearchBarDelegate, DelegateProxyType {
  func setDelegate(to object: UISearchBar) {
    object.delegate = self
  }
}
```

Sadly I am getting two compiler errors:

`'interceptSelectorPublisher' is inaccessible due to 'internal' protection level`

and

`Cannot inherit from non-open class 'DelegateProxy' outside of its defining module`

![Screen Shot 2020-10-01 at 13 50 29](https://user-images.githubusercontent.com/229384/94805708-1cc90280-03ed-11eb-8bd3-4d68caa6bf23.png)

**Comment by freak4pc** [comment]
Fair point, we'll have to make `DelegateProxy` open and `interceptSelectorPublisher` public. 
If I give you a branch will you be able to test it?

**Comment by kevinrenskers** [comment]
No problem

**Comment by freak4pc** [comment]
By the way it might be nicer to push such a proxy as a PR so we could offer it to everyone ;) 
Outside the point, but still relevant

**Comment by freak4pc** [comment]
@kevinrenskers please try https://github.com/CombineCommunity/CombineCocoa/tree/expose-delegateproxy

**Comment by kevinrenskers** [comment]
That was definitely my plan, once I had it done in my own project :)

**Comment by kevinrenskers** [comment]
Alrighty, that works.
