### ISSUE TITLE
Missing required module 'Runtime'

### ISSUE THREAD

**Issue by brandtdaniels** [CombineCommunity/CombineCocoa#33]
I've added CombineCocoa as an SPM dependency to an app being developed in Xcode 12 that supports iOS 13+. 

When I add "import CombineCocoa" to a table view cell, it is highlighted in red and says "Missing required module 'Runtime'"

**Comment by mickamy** [comment]
I got a same error. I also tried with CocoaPods but nothing changed.

**Comment by freak4pc** [comment]
That's interesting! I'll take a look, thank yopu

**Comment by brandtdaniels** [comment]
Any updates on this?

**Comment by brandtdaniels** [comment]
bump

**Comment by SlashDevSlashGnoll** [comment]
We just added CombineCocoa to our project and I'm seeing this as well.  If I learn anything I'll post.

**Comment by freak4pc** [comment]
I just tried with SPM and CocoaPods and am seeing no issues.
Could you share a repro? 

![image](https://user-images.githubusercontent.com/605076/101086256-46530580-35b9-11eb-80c3-fc6b73206cd8.png)

![image](https://user-images.githubusercontent.com/605076/101086266-4a7f2300-35b9-11eb-8fc9-61cc8c5892f0.png)

**Comment by brandtdaniels** [comment]
I am unable to share a repo. Anyone else?

**Comment by SlashDevSlashGnoll** [comment]
Comically, I haven't seen the issue since I posted.   It seems intermittent.

**Comment by mickamy** [comment]
Me neigther.
Could be an issue of Xcode or something like that.
Thoughts? @brandtdaniels

**Comment by brandtdaniels** [comment]
It looks like the issue went away with Xcode 12.2 and CombineCocoa 0.2.2

**Comment by freak4pc** [comment]
Glad to hear it looks good now.

**Comment by Drusy** [comment]
I have the same kind of issue using SPM and Xcode 13
`Umbrella for module 'Runtime' already covers this directory`

**Comment by freak4pc** [comment]
Hey @Drusy - this was already closed (Almost a year ago).
Please open a new issue with a reproducible project.
