### ISSUE TITLE
`didSelectItemPublisher` from collection view only pushes element to latest subscriber

### ISSUE THREAD

**Issue by Linkadi98** [CombineCommunity/CombineCocoa#46]
**Describe the bug**
I had 2 subscribers subscribed to `didSelectItemPublisher` of collection view. One to open another controller, one to call api. But when I tapped on collection view cell, it just emited elements to the latest subscriber, ignored the previous one.

**To Reproduce**
Subscribe 2 subscribers to `didSelectItemPublisher` of collection view and see what happens

**Expected behavior**
`didSelectItemPublisher` emits to all its subscribers

**Device:**
 - Device: iPhone 11 pro
 - OS: macOS BigSur
 - CombineCocoa version: latest

**Comment by freak4pc** [comment]
Thanks to @TTOzzi for fixing this in #47! Should be out in the upcoming release.
