### ISSUE TITLE
Combine Cocoa fails to archive with Xcode 13 RC

### ISSUE THREAD

**Issue by rizwan95** [CombineCommunity/CombineCocoa#56]
**Describe the bug**
When we try to archive a project which has CombineCocoa as a dependency, the archive fails. The following error is generated. 
`
Instance method 'subscribe(on:options:)' requires that 'DispatchQueue' conform to 'Scheduler'
`
**To Reproduce**
1. Add CombineCocoa as a dependency
2. Archive a project

**Expected behavior**
The archive should be generated

**Actual behavior**
Getting the error 
`
Instance method 'subscribe(on:options:)' requires that 'DispatchQueue' conform to 'Scheduler'
`

**Screenshots**
![Screenshot 2021-09-20 at 7 47 52 PM](https://user-images.githubusercontent.com/10910174/134018191-50999c61-b890-4356-ade6-0ab5af0ae8f7.png)

**Comment by iAmrSalman** [comment]
Same here

**Comment by KyleXie** [comment]
I got the same error on Xcode 13.0 release version

**Comment by nikitaame** [comment]
+1

**Comment by cuzv** [comment]
According to [xcode-13-release-notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes), There is a workaround: increase the deployment target of the library to iOS 11 or higher

**Comment by bpollman** [comment]
Theres another workaround you can see being done by the Realm project that lets you keep compatibility. 
https://github.com/realm/realm-cocoa/pull/7401
