### ISSUE TITLE
UITextField textPublisher emitting twice

### ISSUE THREAD

**Issue by vinczebalazs** [CombineCommunity/CombineCocoa#69]
**Describe the bug**
I have come across a strange behaviour, where the textPublisher will emit the same value twice, if there is a subscription to it, and at the end of the subscription when the keyboard is dismissed (if it has not been dismissed before the subscription occurred).

**To Reproduce**
Imagine a save method that starts its chain by subscribing to the textPublisher, sending the value to an API, and on completion popping the view controller that contained the text field. The chain in the save method will be triggered twice, once when the method is invoked, and once when the view controller is popped, as that will cause the text field to dismiss the keyboard and emit an event (not sure which exactly) stating that editing has ended on it. I believe that this is due to the fact that the textPublisher observers both .allEditingEvents and .valueChanged events. 

**Expected behavior**
I would expect the textPublisher to only emit when the actual text has changed, not when editing has ended or anything similar.

**Device:**
 - Probably not OS or device specific.
 - CombineCocoa 0.4.0

**Comment by ahmedgomaa27** [comment]
textPublisher emit for all editing events, so it'll emit when you click on the text field, resign responder from and then edit the text, also if you see the implementation, you'll find that in request(_ demand: Demand) function, subscriber call receive method to send the initial value so that it'll emit for the text publisher when you just subscribe on it

**Comment by vinczebalazs** [comment]
@ahmedgomaa27 Yeah I understand why it's happening, it's just that I would expect a textPublisher to emit when the text changes, should not be releated to other events. Maybe have a different publisher for that? @freak4pc

**Comment by ahmedgomaa27** [comment]
@vinczebalazs  you can use controlEventPublisher and get the value from the text field directly , in this case you send the required event for u

**Comment by freak4pc** [comment]
Hey @vinczebalazs - 
What @ahmedgomaa27 mentioned is correct. The default is tracking all editing events for a text field (copied behavior from RxCocoa here). If you want a specific control event, you can use `controlEventPublisher` directly, as mentioned above.
