### ISSUE TITLE
can't assign Publisher to Button Tapped Publisher  

### ISSUE THREAD

**Issue by knight6700** [CombineCommunity/CombineCocoa#72]
**Describe the bug**
Key path value type 'ReferenceWritableKeyPath<UIButton, Void>' cannot be converted to contextual type 'KeyPath< UIButton, Void>'**To Reproduce**
    var tappedSubject =  CurrentValueSubject<Void,Never>({}())
    var signUPTapped: AnyPublisher<Void, Never> {
        tappedSubject.map {_ in
            self.showAlert()
        }
        .eraseToAnyPublisher()
   }

        viewModel.tappedSubject
            .assign(to: \.tapPublisher, on: signUpButton)
i get error when do this

**Comment by freak4pc** [comment]
I'm not entirely sure what you're trying to do here. 
`signUpButton.tapPublisher` is a Publisher. You can assign anything to it.

**Comment by knight6700** [comment]
> I'm not entirely sure what you're trying to do here. 
> 
> `signUpButton.tapPublisher` is a Publisher. You can't assign anything to it.

I'm trying to assign it to another publisher in viewModel to make navigation i don't want to use @IBAction

**Comment by freak4pc** [comment]
@knight6700 You can't assign anything to a publisher :) Publishers are read-only entities you can `sink` on to wait for their values.

Your question isn't related to CombineCocoa directly, so I suggest either trying StackOverflow or one of the available iOS Slack channels.

Thanks!
